{{- if .Values.xampp.enabled -}}
{{- if .Values.xampp.ingressRoute.enabled -}}
---
apiVersion: traefik.io/v1alpha1
# or 
# apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: xampp-{{.Values.environment }}-iroute
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
spec:
  entryPoints:
    - web
    - websecure
    # - traefik
  routes:
    - kind: Rule
      match: Host(`{{.Values.environment }}-xampp.{{.Values.applicationHostName }}`) && PathPrefix(`/`)
      services:
        - name: {{ include "xampp.fullname" . }}-{{.Values.environment }}-svc
          port: 80
          kind: Service
      {{- if .Values.xampp.ingressRoute.middlewareEnabled -}}
      middlewares:
        - name: xampp-{{.Values.environment }}-mw
      {{- end }}
---
{{- if .Values.xampp.ingressRoute.middlewareEnabled -}}
apiVersion: traefik.io/v1alpha1
# or 
# apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: xampp-{{.Values.environment }}-mw
spec:
  stripPrefix:
    prefixes:
      - "/"

#  tls:
#    secretName: local-example-com-staging-tls
{{- end }}
{{- end }}
{{- end }}